webdev:
  build: web/.
  ports:
    - "9000"
    - "8081"
    - "35279"
apidev:
  build: go/.
  ports:
    - "9000"
    - "8080"
proxy:
  build: proxy/.
  ports:
    - "8080:8080"
  links:
    - webdev
    - apidev
