webdev:
  build: web/.
  ports:
    - "9000:9000"
    - "8081:8081"
    - "35279:35279"
apidev:
  build: go/.
  ports:
    - "9001:9000"
    - "8080:8080"
proxy:
  build: proxy/.
  ports:
    - "80:80"
  links:
    - webdev
    - apidev
